gappih=5
gappiv=5
gappoh=10
gappov=10
scratchpad_width_ratio=0.8
scratchpad_height_ratio=0.9
borderpx=4
rootcolor=0xb08ce0ff   
bordercolor=0xb08ce0ff 
dropcolor=0x89b4fa55     
splitcolor=0xa6e3a1ff   
focuscolor=0xcba6f7ff
maximizescreencolor=0x89b4faff  
urgentcolor=0xf38ba8ff   
scratchpadcolor=0x89dcebff 
globalcolor=0xf5c2e7ff   
overlaycolor=0xa6e3a1ff 
