source = ~/.config/mango/env.conf
source = ~/.config/mango/effect.conf
source = ~/.config/mango/animation.conf
source = ~/.config/mango/misc.conf
source = ~/.config/mango/keyboard.conf
source = ~/.config/mango/trackpad.conf
source = ~/.config/mango/mouse.conf
source = ~/.config/mango/appearance.conf
source = ~/.config/mango/layout.conf
source = ~/.config/mango/bind.conf
source = ~/.config/mango/exec.conf
source = ~/.config/mango/tag.conf
source = ~/.config/mango/monitor.conf
